spring.application.name=VimeoMiner

sever.port=8081
logging.level.aiss.vimeoMiner.VimeoMiner.controller=DEBUG
vimeominer.baseuri = https://api.vimeo.com
vimeominer.token = 0fa07374f9fb285dd2a22e1e629613ee

vimeominer.maxVideos = 10
vimeominer.maxComments = 10

videominer.uri = https://localhost:8080/videominer/channels